### ISSUE TITLE
Error receiving data from the seedlink server

### ISSUE THREAD

**Issue by marco-bertelli** [Jollyfant/node-seedlink-data-proxy#1]
hi, i am doing a very similar project, all wark (handshake is goiing good i see 3 OK), but after end my socket don't receive the data (in telnet i see it)

**Comment by Jollyfant** [comment]
Hello Marco! Can you run the server using `node index.js` and then open up the example in the `examples/index.html` folder? It should connect to a public seedink server at `eida.orfeus-eu.org:18000` and write received data to `console.log`. You may have to change `0.0.0.0:8089` to `127.0.0.1:8089` in the JavaScript.

In order to use your own Seedlink server you should modify `channel-config.json` to configure the rooms that can be subscribed to. Then, in the client-side JavaScript you need to write to the websocket: `{"subscribe": "some-room"}` in order to receive data.

**Comment by marco-bertelli** [comment]
thanks man, i made a mistake parsing strings commands to seddlinks commands.
All ok thanks for the answer

**Comment by Jollyfant** [comment]
Great!
